### ISSUE TITLE
Incomplete version?

### ISSUE THREAD

**Issue by TheoMarque** [iitggithub/iperf-web#2]
I get clone from git repository and run by docker-compose
after this, web interface is scrabled but:
1. If i pick Docker engine to test I have:
```
Test execution begins...
Traceback (most recent call last):
  File "/usr/local/bin/run20.py", line 55, in 
    for char in client.containers.run(image, args.commands, remove=True):
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 697, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 741, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 447, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 457, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 248, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 185, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
Test execution has ended...
```
2. If I pick Iperf:
command not found (after manual install by exec [apt update && apt instal iperf -y]- is OK.

**Comment by iitggithub** [comment]
Yes it was incomplete. I mostly put it on github so i didn't lose what i was working on and didn't realise people would actually use it. My apologies.

I've completely revamped the web interface now. The docker container uses Python3 and runs a web interface via Flask. It now works as expected and you can use iperf2 or iperf3.

I recommend trying it.
